import { DefaultTheme } from 'styled-components';

export const darkTheme: DefaultTheme = {
  background: '#171820',
  foreground: '#1D1E26',
  overlay: '#ffffff10',
  text: '#BDBDC7',
  textSecondary: '#656576',
  primary: '#886FCF',
  active: '#31A24C',
  border: '#1F2029',
  fontFamily: `'Montserrat', sans-serif`,
  fontFamilySecondary: `'Fira Code', monospace`,
  fontSizeXxs: '0.75rem',
  fontSizeXs: '0.8125rem',
  fontSizeSm: '0.875rem',
  fontSizeMd: '1rem',
  fontSizeLg: '1.25rem',
  fontSizeXl: '1.5rem',
  fontSizeXxl: '2rem',
  fontSizeXxxl: '4rem',
  fontWeightLight: '300',
  fontWeightRegular: '400',
  fontWeightMedium: '500',
  fontWeightSemiBold: '600',
  fontWeightBold: '700',
  fontWeightExtraBold: '800',
  fontWeightBlack: '900',
  transition: 'all 150ms ease-in-out',
};
